// Code generated by modusGraphGen. DO NOT EDIT.

// TODO: Generate Kong CLI with subcommands for each entity.
// This is a placeholder that generates a valid main.go.
package main

import "fmt"

func main() {
	fmt.Println("movies CLI - not yet implemented")
	fmt.Println("Entities:")
	fmt.Println("  - Actor")
	fmt.Println("  - ContentRating")
	fmt.Println("  - Country")
	fmt.Println("  - Director")
	fmt.Println("  - Film")
	fmt.Println("  - Genre")
	fmt.Println("  - Location")
	fmt.Println("  - Performance")
	fmt.Println("  - Rating")
}
