// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// ActorClient provides typed CRUD operations for Actor entities.
type ActorClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Actor by its UID.
func (c *ActorClient) Get(ctx context.Context, uid string) (*Actor, error) {
	var result Actor
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Actor into the database.
func (c *ActorClient) Add(ctx context.Context, v *Actor) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Actor in the database. The UID field must be set.
func (c *ActorClient) Update(ctx context.Context, v *Actor) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Actor with the given UID from the database.
func (c *ActorClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Actor entities whose Name matches term using fulltext search.
func (c *ActorClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Actor, error) {
	var results []Actor
	q := c.conn.Query(ctx, Actor{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Actor entities with optional pagination.
func (c *ActorClient) List(ctx context.Context, opts ...PageOption) ([]Actor, error) {
	var results []Actor
	q := c.conn.Query(ctx, Actor{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
