// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// ActorOption is a functional option for configuring Actor mutations.
type ActorOption func(*Actor)

// WithActorName sets the Name field on a Actor.
func WithActorName(v string) ActorOption {
	return func(e *Actor) {
		e.Name = v
	}
}

// ApplyActorOptions applies the given options to a Actor.
func ApplyActorOptions(e *Actor, opts ...ActorOption) {
	for _, opt := range opts {
		opt(e)
	}
}
