// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph"
)

// Client provides typed access to the movies data model.
type Client struct {
	conn          modusgraph.Client
	Actor         *ActorClient
	ContentRating *ContentRatingClient
	Country       *CountryClient
	Director      *DirectorClient
	Film          *FilmClient
	Genre         *GenreClient
	Location      *LocationClient
	Performance   *PerformanceClient
	Rating        *RatingClient
}

// New creates a new Client connected to the graph database at connStr.
func New(connStr string, opts ...modusgraph.ClientOpt) (*Client, error) {
	conn, err := modusgraph.NewClient(connStr, opts...)
	if err != nil {
		return nil, err
	}
	return NewFromClient(conn), nil
}

// NewFromClient creates a new Client from an existing modusgraph.Client connection.
func NewFromClient(conn modusgraph.Client) *Client {
	return &Client{
		conn:          conn,
		Actor:         &ActorClient{conn: conn},
		ContentRating: &ContentRatingClient{conn: conn},
		Country:       &CountryClient{conn: conn},
		Director:      &DirectorClient{conn: conn},
		Film:          &FilmClient{conn: conn},
		Genre:         &GenreClient{conn: conn},
		Location:      &LocationClient{conn: conn},
		Performance:   &PerformanceClient{conn: conn},
		Rating:        &RatingClient{conn: conn},
	}
}

// Close releases all resources used by the client.
func (c *Client) Close() {
	c.conn.Close()
}
