// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// ContentRatingClient provides typed CRUD operations for ContentRating entities.
type ContentRatingClient struct {
	conn modusgraph.Client
}

// Get retrieves a single ContentRating by its UID.
func (c *ContentRatingClient) Get(ctx context.Context, uid string) (*ContentRating, error) {
	var result ContentRating
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new ContentRating into the database.
func (c *ContentRatingClient) Add(ctx context.Context, v *ContentRating) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing ContentRating in the database. The UID field must be set.
func (c *ContentRatingClient) Update(ctx context.Context, v *ContentRating) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the ContentRating with the given UID from the database.
func (c *ContentRatingClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds ContentRating entities whose Name matches term using fulltext search.
func (c *ContentRatingClient) Search(ctx context.Context, term string, opts ...PageOption) ([]ContentRating, error) {
	var results []ContentRating
	q := c.conn.Query(ctx, ContentRating{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves ContentRating entities with optional pagination.
func (c *ContentRatingClient) List(ctx context.Context, opts ...PageOption) ([]ContentRating, error) {
	var results []ContentRating
	q := c.conn.Query(ctx, ContentRating{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
