// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// ContentRatingOption is a functional option for configuring ContentRating mutations.
type ContentRatingOption func(*ContentRating)

// WithContentRatingName sets the Name field on a ContentRating.
func WithContentRatingName(v string) ContentRatingOption {
	return func(e *ContentRating) {
		e.Name = v
	}
}

// ApplyContentRatingOptions applies the given options to a ContentRating.
func ApplyContentRatingOptions(e *ContentRating, opts ...ContentRatingOption) {
	for _, opt := range opts {
		opt(e)
	}
}
