// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// CountryOption is a functional option for configuring Country mutations.
type CountryOption func(*Country)

// WithCountryName sets the Name field on a Country.
func WithCountryName(v string) CountryOption {
	return func(e *Country) {
		e.Name = v
	}
}

// ApplyCountryOptions applies the given options to a Country.
func ApplyCountryOptions(e *Country, opts ...CountryOption) {
	for _, opt := range opts {
		opt(e)
	}
}
