// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// CountryClient provides typed CRUD operations for Country entities.
type CountryClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Country by its UID.
func (c *CountryClient) Get(ctx context.Context, uid string) (*Country, error) {
	var result Country
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Country into the database.
func (c *CountryClient) Add(ctx context.Context, v *Country) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Country in the database. The UID field must be set.
func (c *CountryClient) Update(ctx context.Context, v *Country) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Country with the given UID from the database.
func (c *CountryClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Country entities whose Name matches term using fulltext search.
func (c *CountryClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Country, error) {
	var results []Country
	q := c.conn.Query(ctx, Country{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Country entities with optional pagination.
func (c *CountryClient) List(ctx context.Context, opts ...PageOption) ([]Country, error) {
	var results []Country
	q := c.conn.Query(ctx, Country{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
