// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// DirectorClient provides typed CRUD operations for Director entities.
type DirectorClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Director by its UID.
func (c *DirectorClient) Get(ctx context.Context, uid string) (*Director, error) {
	var result Director
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Director into the database.
func (c *DirectorClient) Add(ctx context.Context, v *Director) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Director in the database. The UID field must be set.
func (c *DirectorClient) Update(ctx context.Context, v *Director) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Director with the given UID from the database.
func (c *DirectorClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Director entities whose Name matches term using fulltext search.
func (c *DirectorClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Director, error) {
	var results []Director
	q := c.conn.Query(ctx, Director{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Director entities with optional pagination.
func (c *DirectorClient) List(ctx context.Context, opts ...PageOption) ([]Director, error) {
	var results []Director
	q := c.conn.Query(ctx, Director{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
