// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// DirectorOption is a functional option for configuring Director mutations.
type DirectorOption func(*Director)

// WithDirectorName sets the Name field on a Director.
func WithDirectorName(v string) DirectorOption {
	return func(e *Director) {
		e.Name = v
	}
}

// ApplyDirectorOptions applies the given options to a Director.
func ApplyDirectorOptions(e *Director, opts ...DirectorOption) {
	for _, opt := range opts {
		opt(e)
	}
}
