// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// FilmClient provides typed CRUD operations for Film entities.
type FilmClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Film by its UID.
func (c *FilmClient) Get(ctx context.Context, uid string) (*Film, error) {
	var result Film
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Film into the database.
func (c *FilmClient) Add(ctx context.Context, v *Film) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Film in the database. The UID field must be set.
func (c *FilmClient) Update(ctx context.Context, v *Film) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Film with the given UID from the database.
func (c *FilmClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Film entities whose Name matches term using fulltext search.
func (c *FilmClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Film, error) {
	var results []Film
	q := c.conn.Query(ctx, Film{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Film entities with optional pagination.
func (c *FilmClient) List(ctx context.Context, opts ...PageOption) ([]Film, error) {
	var results []Film
	q := c.conn.Query(ctx, Film{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
