// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "time"

// FilmOption is a functional option for configuring Film mutations.
type FilmOption func(*Film)

// WithFilmName sets the Name field on a Film.
func WithFilmName(v string) FilmOption {
	return func(e *Film) {
		e.Name = v
	}
}

// WithFilmInitialReleaseDate sets the InitialReleaseDate field on a Film.
func WithFilmInitialReleaseDate(v time.Time) FilmOption {
	return func(e *Film) {
		e.InitialReleaseDate = v
	}
}

// WithFilmTagline sets the Tagline field on a Film.
func WithFilmTagline(v string) FilmOption {
	return func(e *Film) {
		e.Tagline = v
	}
}

// ApplyFilmOptions applies the given options to a Film.
func ApplyFilmOptions(e *Film, opts ...FilmOption) {
	for _, opt := range opts {
		opt(e)
	}
}
