// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// GenreOption is a functional option for configuring Genre mutations.
type GenreOption func(*Genre)

// WithGenreName sets the Name field on a Genre.
func WithGenreName(v string) GenreOption {
	return func(e *Genre) {
		e.Name = v
	}
}

// ApplyGenreOptions applies the given options to a Genre.
func ApplyGenreOptions(e *Genre, opts ...GenreOption) {
	for _, opt := range opts {
		opt(e)
	}
}
