// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// GenreClient provides typed CRUD operations for Genre entities.
type GenreClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Genre by its UID.
func (c *GenreClient) Get(ctx context.Context, uid string) (*Genre, error) {
	var result Genre
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Genre into the database.
func (c *GenreClient) Add(ctx context.Context, v *Genre) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Genre in the database. The UID field must be set.
func (c *GenreClient) Update(ctx context.Context, v *Genre) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Genre with the given UID from the database.
func (c *GenreClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Genre entities whose Name matches term using fulltext search.
func (c *GenreClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Genre, error) {
	var results []Genre
	q := c.conn.Query(ctx, Genre{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Genre entities with optional pagination.
func (c *GenreClient) List(ctx context.Context, opts ...PageOption) ([]Genre, error) {
	var results []Genre
	q := c.conn.Query(ctx, Genre{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
