// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// LocationClient provides typed CRUD operations for Location entities.
type LocationClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Location by its UID.
func (c *LocationClient) Get(ctx context.Context, uid string) (*Location, error) {
	var result Location
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Location into the database.
func (c *LocationClient) Add(ctx context.Context, v *Location) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Location in the database. The UID field must be set.
func (c *LocationClient) Update(ctx context.Context, v *Location) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Location with the given UID from the database.
func (c *LocationClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Location entities whose Name matches term using fulltext search.
func (c *LocationClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Location, error) {
	var results []Location
	q := c.conn.Query(ctx, Location{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Location entities with optional pagination.
func (c *LocationClient) List(ctx context.Context, opts ...PageOption) ([]Location, error) {
	var results []Location
	q := c.conn.Query(ctx, Location{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
