// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// LocationOption is a functional option for configuring Location mutations.
type LocationOption func(*Location)

// WithLocationName sets the Name field on a Location.
func WithLocationName(v string) LocationOption {
	return func(e *Location) {
		e.Name = v
	}
}

// WithLocationLoc sets the Loc field on a Location.
func WithLocationLoc(v []float64) LocationOption {
	return func(e *Location) {
		e.Loc = v
	}
}

// WithLocationEmail sets the Email field on a Location.
func WithLocationEmail(v string) LocationOption {
	return func(e *Location) {
		e.Email = v
	}
}

// ApplyLocationOptions applies the given options to a Location.
func ApplyLocationOptions(e *Location, opts ...LocationOption) {
	for _, opt := range opts {
		opt(e)
	}
}
