// Code generated by modusGraphGen. DO NOT EDIT.

package movies

const defaultPageSize = 50

// PageOption configures pagination for queries.
type PageOption interface {
	applyPage(cfg *pageConfig)
}

type pageConfig struct {
	first  int
	offset int
}

type firstOption int

func (f firstOption) applyPage(cfg *pageConfig) {
	cfg.first = int(f)
}

// First limits the number of results returned.
func First(n int) PageOption {
	return firstOption(n)
}

type offsetOption int

func (o offsetOption) applyPage(cfg *pageConfig) {
	cfg.offset = int(o)
}

// Offset skips the first n results.
func Offset(n int) PageOption {
	return offsetOption(n)
}
