// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// PerformanceOption is a functional option for configuring Performance mutations.
type PerformanceOption func(*Performance)

// WithPerformanceCharacterNote sets the CharacterNote field on a Performance.
func WithPerformanceCharacterNote(v string) PerformanceOption {
	return func(e *Performance) {
		e.CharacterNote = v
	}
}

// ApplyPerformanceOptions applies the given options to a Performance.
func ApplyPerformanceOptions(e *Performance, opts ...PerformanceOption) {
	for _, opt := range opts {
		opt(e)
	}
}
