// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// PerformanceClient provides typed CRUD operations for Performance entities.
type PerformanceClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Performance by its UID.
func (c *PerformanceClient) Get(ctx context.Context, uid string) (*Performance, error) {
	var result Performance
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Performance into the database.
func (c *PerformanceClient) Add(ctx context.Context, v *Performance) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Performance in the database. The UID field must be set.
func (c *PerformanceClient) Update(ctx context.Context, v *Performance) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Performance with the given UID from the database.
func (c *PerformanceClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// List retrieves Performance entities with optional pagination.
func (c *PerformanceClient) List(ctx context.Context, opts ...PageOption) ([]Performance, error) {
	var results []Performance
	q := c.conn.Query(ctx, Performance{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
