// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// RatingOption is a functional option for configuring Rating mutations.
type RatingOption func(*Rating)

// WithRatingName sets the Name field on a Rating.
func WithRatingName(v string) RatingOption {
	return func(e *Rating) {
		e.Name = v
	}
}

// ApplyRatingOptions applies the given options to a Rating.
func ApplyRatingOptions(e *Rating, opts ...RatingOption) {
	for _, opt := range opts {
		opt(e)
	}
}
