// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// RatingClient provides typed CRUD operations for Rating entities.
type RatingClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Rating by its UID.
func (c *RatingClient) Get(ctx context.Context, uid string) (*Rating, error) {
	var result Rating
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Rating into the database.
func (c *RatingClient) Add(ctx context.Context, v *Rating) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Rating in the database. The UID field must be set.
func (c *RatingClient) Update(ctx context.Context, v *Rating) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Rating with the given UID from the database.
func (c *RatingClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Search finds Rating entities whose Name matches term using fulltext search.
func (c *RatingClient) Search(ctx context.Context, term string, opts ...PageOption) ([]Rating, error) {
	var results []Rating
	q := c.conn.Query(ctx, Rating{}).
		Filter(`alloftext(name, "` + term + `")`).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}

// List retrieves Rating entities with optional pagination.
func (c *RatingClient) List(ctx context.Context, opts ...PageOption) ([]Rating, error) {
	var results []Rating
	q := c.conn.Query(ctx, Rating{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
